# Generated by Django 4.2.6 on 2023-10-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_patient_pseudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='patient',
        ),
    ]
