# Generated by Django 4.2.6 on 2023-10-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_rename_user_patient_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corps', models.TextField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.psy')),
            ],
        ),
        migrations.CreateModel(
            name='AppelClientTwilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_twilio_demo', models.URLField()),
                ('calling_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.psy')),
                ('calling_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
    ]
