# Generated by Django 4.2.6 on 2023-10-22 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_patient_patient'),
        ('zoomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_sid', models.CharField(max_length=34, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], default='pending', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls_as_patient', to='accounts.patient')),
                ('psy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls_as_psy', to='accounts.psy')),
            ],
        ),
    ]
