# Generated by Django 4.2.6 on 2023-10-23 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_patient_patient'),
        ('zoomapp', '0002_videocall'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('psy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.psy')),
            ],
        ),
    ]
